### ISSUE TITLE
Start/Restart an optimization with a deap population 

### ISSUE THREAD

**Issue by anirban6908** [BlueBrain/BluePyOpt#252]
Hi,
I would like to start/restart optimization with a population rather than just specifying a random seed. This would really help if after **_n_** generations I want to change the fitness function and reinitialize the optimization with the population at the **_n_**_th generation.

Thanks

**Comment by roybens** [comment]
Hi i solved this locally by changing line 102 at 
bluepyopt\deapext\algorithms.py to:
 cp = pickle.load(open(cp_filename, "rb"))
just adding a b for the binary worked for me

**Comment by wvangeit** [comment]
@roybens this is for restarting from a checkpoint.
If I'm not mistaken I assume @anirban6908 just wants to be able to provide a list of individuals when starting an optimization ?

**Comment by roybens** [comment]
But wouldn't a checkpoint load do just that? start the optimization from the last population or continue it as it was when the checkpoint was saved. Then you can change the fitness and it should go smoothly. I added objective and continued an optimization from checkpoint it seemed to go well. Regardless I think there is unexpected behavior in loading check point since it misses the binary flag in the load.

**Comment by anirban6908** [comment]
Hi @roybens Right now the checkpoint load would not work if the fitness function is modified e.g., adding a new feature to MOO from previous run to current run. 
@wvangeit  I added this functionality to my fork. If you think this could be useful I can send a PR.
Thanks

**Comment by wvangeit** [comment]
@anirban6908 definitely, feel free to create a PR

**Comment by wvangeit** [comment]
(that was my thinking also, loading from checkpoint puts some requirements on the optimization that saves/loads the checkpoint). Have a pure list of individuals removes these constraints)

**Comment by wvangeit** [comment]
@DrTaDa could you have a look at PR, and merge if it's ok like this.
