### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ASVG** [BlueBrain/BluePyOpt#367]
I have a question on the Release version of BluePyOpt. It appears as though the release of new versions is not officially published? Or it appears different from other BBP software releases. Could someone look into it and see if it needs proper updates of versions please? Thank you. A

**Comment by wvangeit** [comment]
All the releases are list here: https://pypi.org/project/bluepyopt/#history

**Comment by ASVG** [comment]
Many thanks for the info. https://pypi.org/project/bluepyopt/#history I suppose this link is not a part of Github system?

**Comment by wvangeit** [comment]
No, that's the official python repository. It's the only place where you can be sure the releases can be used by all python users.

**Comment by ASVG** [comment]
IC. Is there a way to release (sync) it at/with Github as well? The way release is publicised looks different from others... (e.g., BluePyEfe)

**Comment by wvangeit** [comment]
I assume it can be automated, but I'm not sure anybody at bbp is doing that. What is the difference between bpopt and bpefe?
https://github.com/BlueBrain/BluePyEfe/releases
and
https://github.com/BlueBrain/BluePyOpt/releases
bpefe has a manual release at some point because I needed a DOI for the HBP, but that should be avoided since it's done manually.

**Comment by ASVG** [comment]
OK. I have found a solution to this. Many thanks...
